### PR TITLE
Update f11 to new arrival format

### PR DESCRIPTION
**Pull request by jessie846**

### CODE REVIEW

**Comment by mmp** [comment]
There seem to be some errors in MSY; was it intended to include that?

```
File scenarios/msy.json / airports / KMSY: The entry "exit_categorie" is not an expected JSON object. Is it misspelled?
File scenarios/msy.json / airports / KMSY / approaches / L11: The entry "name" is not an expected JSON object. Is it misspelled?
File scenarios/msy.json / airports / KMSY / approaches / L29: The entry "name" is not an expected JSON object. Is it misspelled?
File scenarios/msy.json / airports / KMSY / approaches / L2: The entry "name" is not an expected JSON object. Is it misspelled?
File scenarios/msy.json / airports / KMSY / approaches / L20: The entry "name" is not an expected JSON object. Is it misspelled?
File scenarios/msy.json / airports / KNEW / approaches / R6L: The entry "'tower_controller" is not an expected JSON object. Is it misspelled?
```

**Comment by jessie846** [comment]
@mmp Could have sworn that I had removed MSY but apparently not, MSY was not meant to be inclued.

**Comment by mmp** [comment]
Ok, great, I dropped msy.json but it looks like there are still some issues with f11:
```
TRACON F11 / Scenario group KMCO: cannot specify both "arrival_groups" and "inbound_flows"
TRACON F11 / Scenario group KMCO / Scenario KMCO West Feeder North / Inbound flow GRNCH5_LNU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO West Feeder North / Inbound flow PRICY3_LNU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO Combined Feeder North / Inbound flow ALYNA4_BNU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO Combined Feeder North / Inbound flow GRNCH5_LNU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO Combined Feeder North / Inbound flow PRICY3_LNU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO Combined Feeder North / Inbound flow RIDES2_BNU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO Combined Feeder North / Inbound flow SNFLD3_BNU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO East Feeder North / Inbound flow ALYNA4_BNU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO East Feeder North / Inbound flow RIDES2_BNU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO East Feeder North / Inbound flow SNFLD3_BNU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North Final / Inbound flow GRNCH_NFINAL: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North Final / Inbound flow PRICY3_NFINAL: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North Final / Inbound flow RIDES2_NFINAL: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North Final / Inbound flow SNFLD3_NFINAL: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / "multi_controllers": split "default" / MCO_D_APP: no inbound flows in "GOOFY7" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / "multi_controllers": split "default" / MCO_D_APP: no inbound flows in "JOKRS3" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / "multi_controllers": split "default" / MCO_A_APP: no inbound flows in "EAST_COAST_OVERFLIGHTN" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / "multi_controllers": split "default" / MCO_K_APP: no inbound flows in "EAST_COAST_OVERFLIGHTS" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / "multi_controllers": split "default" / MCO_E_DEP: no inbound flows in "DADES1" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / "multi_controllers": split "default" / MCO_B_APP: no inbound flows in "SNFLD3" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / "multi_controllers": split "default" / MCO_B_APP: no inbound flows in "RIDES2" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / "multi_controllers": split "default" / MCO_B_APP: no inbound flows in "BITHO7" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / "multi_controllers": split "default" / MCO_L_APP: no inbound flows in "PRICY3" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / "multi_controllers": split "default" / MCO_L_APP: no inbound flows in "GRNCH5" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / "multi_controllers": split "default" / MCO_L_APP: no inbound flows in "SHREK2E" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / "multi_controllers": split "default" / MCO_L_APP: no inbound flows in "SHREK2.MCO" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / "multi_controllers": split "default" / MCO_L_APP: no inbound flows in "JOKRS3.MCO" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / "multi_controllers": split "default" / MCO_V_APP: no inbound flows in "TTHOR3" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / Inbound flow BITHO7: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / Inbound flow DADES1: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / Inbound flow EAST_COAST_OVERFLIGHTN: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / Inbound flow EAST_COAST_OVERFLIGHTS: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / Inbound flow GOOFY7: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / Inbound flow GRNCH5: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / Inbound flow JOKRS3: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / Inbound flow JOKRS3.MCO: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / Inbound flow PRICY3: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / Inbound flow RIDES2: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / Inbound flow SHREK2.MCO: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / Inbound flow SHREK2E: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / Inbound flow SNFLD3: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO North + Sat East / Inbound flow TTHOR3: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO Combined Feeder South / Inbound flow ALYNA4_BSU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO Combined Feeder South / Inbound flow GRNCH5_LSU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO Combined Feeder South / Inbound flow GTOUT1_BSU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO Combined Feeder South / Inbound flow PRICY3_LSU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO Combined Feeder South / Inbound flow RIDES2_BSU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO East Feeder South / Inbound flow ALYNA4_BSU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO East Feeder South / Inbound flow GTOUT1_BSU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO East Feeder South / Inbound flow RIDES2_BSU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO West Feeder South / Inbound flow GRNCH5_LSU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO West Feeder South / Inbound flow PRICY3_LSU: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / "multi_controllers": split "default" / MCO_D_APP: no inbound flows in "GOOFY7" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / "multi_controllers": split "default" / MCO_D_APP: no inbound flows in "JOKRS3" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / "multi_controllers": split "default" / MCO_B_APP: no inbound flows in "GTOUT1" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / "multi_controllers": split "default" / MCO_B_APP: no inbound flows in "RIDES2" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / "multi_controllers": split "default" / MCO_B_APP: no inbound flows in "BITHO7" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / "multi_controllers": split "default" / MCO_B_APP: no inbound flows in "SNFLD3" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / "multi_controllers": split "default" / MCO_L_APP: no inbound flows in "PRICY3" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / "multi_controllers": split "default" / MCO_L_APP: no inbound flows in "GRNCH5" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / "multi_controllers": split "default" / MCO_L_APP: no inbound flows in "SHREK2W" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / "multi_controllers": split "default" / MCO_L_APP: no inbound flows in "SHREK2.MCO" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / "multi_controllers": split "default" / MCO_L_APP: no inbound flows in "JOKRS3.MCO" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / "multi_controllers": split "default" / MCO_A_APP: no inbound flows in "EAST_COAST_OVERFLIGHTN" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / "multi_controllers": split "default" / MCO_K_APP: no inbound flows in "EAST_COAST_OVERFLIGHTS" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / "multi_controllers": split "default" / MCO_E_DEP: no inbound flows in "DADES1" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / "multi_controllers": split "default" / MCO_V_APP: no inbound flows in "TTHOR3" have handoffs
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / Inbound flow BITHO7: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / Inbound flow DADES1: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / Inbound flow EAST_COAST_OVERFLIGHTN: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / Inbound flow EAST_COAST_OVERFLIGHTS: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / Inbound flow GOOFY7: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / Inbound flow GRNCH5: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / Inbound flow GTOUT1: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / Inbound flow JOKRS3: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / Inbound flow JOKRS3.MCO: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / Inbound flow PRICY3: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / Inbound flow RIDES2: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / Inbound flow SHREK2.MCO: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / Inbound flow SHREK2W: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / Inbound flow SNFLD3: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South + Sat West / Inbound flow TTHOR3: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South Final / Inbound flow ALYNA4_SFINAL: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South Final / Inbound flow FINAL_S_GRNCH5: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South Final / Inbound flow GTOUT1_SFINAL: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South Final / Inbound flow PRICY3_SFINAL: inbound flow not found
TRACON F11 / Scenario group KMCO / Scenario KMCO South Final / Inbound flow RIDES2_SFINAL: inbound flow not found
```

**Comment by jessie846** [comment]
Weird, I guess I must have messed up the branch. I will send you the updated file in DMs on discord

**Pull request closed without merging**
