### PR TITLE
Add p31 josh

### PR DESCRIPTION
**Pull request by JoshAviation**

### CODE REVIEW

**Comment by mmp** [comment]
Is this the latest version (and does the latest version work for you)? There are some errors in the JSON like:
```json
           "departure_routes": {
                 "17" {
```
a colon is missing after the "17"

**Comment by JoshAviation** [comment]
Sorry, it is my first time working on a vice file and it has been a while
since coding in JSON.

**Comment by jessie846** [comment]
@mmp this is ready to be merged

**Comment by mmp** [comment]
Looks great, thanks!

**Comment by mmp** [comment]
@JoshAviation how do you want to be listed in the credits (and what's your discord id so I can give you the facility data developer rule on the vice discord)?

**Comment by JoshAviation** [comment]
My discord id is 699418447175483436, with the username of joshuaav. Thank you.

**Comment by mmp** [comment]
Thanks; role added on the discord! Also, when people click the "info" button on the right side of the menubar, a window comes up that lists all of the contributors by name. Let me know if you're like your full name there, a shortened version, or something else.

**Comment by JoshAviation** [comment]
I’ll just take Josh Lambert

**Comment by JoshAviation** [comment]
Thank you for your help through this process, working with vice has been so
much easier than other projects before.

**Comment by mmp** [comment]
Great, thanks, I've added you to the credits there as well. And I'm glad it's been a good experience working with vice!

**Pull request merged**
